/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CdpRequestBuilderNavigationMetadata, type CdpRequestBuilder } from './cdp/index.js';
// @ts-ignore
import { CrawlRequestBuilderNavigationMetadata, type CrawlRequestBuilder } from './crawl/index.js';
// @ts-ignore
import { CrawlRunsRequestBuilderNavigationMetadata, CrawlRunsRequestBuilderRequestsMetadata, type CrawlRunsRequestBuilder } from './crawlRuns/index.js';
// @ts-ignore
import { DatasetsRequestBuilderNavigationMetadata, DatasetsRequestBuilderRequestsMetadata, type DatasetsRequestBuilder } from './datasets/index.js';
// @ts-ignore
import { ExtractRequestBuilderRequestsMetadata, type ExtractRequestBuilder } from './extract/index.js';
// @ts-ignore
import { KvRequestBuilderNavigationMetadata, type KvRequestBuilder } from './kv/index.js';
// @ts-ignore
import { MapRequestBuilderRequestsMetadata, type MapRequestBuilder } from './map/index.js';
// @ts-ignore
import { PageRequestBuilderNavigationMetadata, type PageRequestBuilder } from './page/index.js';
// @ts-ignore
import { ProfilesRequestBuilderNavigationMetadata, ProfilesRequestBuilderRequestsMetadata, type ProfilesRequestBuilder } from './profiles/index.js';
// @ts-ignore
import { ProxyProvidersRequestBuilderRequestsMetadata, type ProxyProvidersRequestBuilder } from './proxyProviders/index.js';
// @ts-ignore
import { RecordingsRequestBuilderNavigationMetadata, RecordingsRequestBuilderRequestsMetadata, type RecordingsRequestBuilder } from './recordings/index.js';
// @ts-ignore
import { SchedulesRequestBuilderNavigationMetadata, SchedulesRequestBuilderRequestsMetadata, type SchedulesRequestBuilder } from './schedules/index.js';
// @ts-ignore
import { ScrapeRequestBuilderNavigationMetadata, ScrapeRequestBuilderRequestsMetadata, type ScrapeRequestBuilder } from './scrape/index.js';
// @ts-ignore
import { ScreenshotBlobsRequestBuilderNavigationMetadata, type ScreenshotBlobsRequestBuilder } from './screenshotBlobs/index.js';
// @ts-ignore
import { SearchRequestBuilderRequestsMetadata, type SearchRequestBuilder } from './search/index.js';
// @ts-ignore
import { SessionsRequestBuilderNavigationMetadata, SessionsRequestBuilderRequestsMetadata, type SessionsRequestBuilder } from './sessions/index.js';
// @ts-ignore
import { StorageStatesRequestBuilderNavigationMetadata, StorageStatesRequestBuilderRequestsMetadata, type StorageStatesRequestBuilder } from './storageStates/index.js';
// @ts-ignore
import { type WebhooksRequestBuilder, WebhooksRequestBuilderNavigationMetadata, WebhooksRequestBuilderRequestsMetadata } from './webhooks/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1
 */
export interface V1RequestBuilder extends BaseRequestBuilder<V1RequestBuilder> {
    /**
     * The cdp property
     */
    get cdp(): CdpRequestBuilder;
    /**
     * The crawl property
     */
    get crawl(): CrawlRequestBuilder;
    /**
     * The crawlRuns property
     */
    get crawlRuns(): CrawlRunsRequestBuilder;
    /**
     * The datasets property
     */
    get datasets(): DatasetsRequestBuilder;
    /**
     * The extract property
     */
    get extract(): ExtractRequestBuilder;
    /**
     * The kv property
     */
    get kv(): KvRequestBuilder;
    /**
     * The map property
     */
    get map(): MapRequestBuilder;
    /**
     * The page property
     */
    get page(): PageRequestBuilder;
    /**
     * The profiles property
     */
    get profiles(): ProfilesRequestBuilder;
    /**
     * The proxyProviders property
     */
    get proxyProviders(): ProxyProvidersRequestBuilder;
    /**
     * The recordings property
     */
    get recordings(): RecordingsRequestBuilder;
    /**
     * The schedules property
     */
    get schedules(): SchedulesRequestBuilder;
    /**
     * The scrape property
     */
    get scrape(): ScrapeRequestBuilder;
    /**
     * The screenshotBlobs property
     */
    get screenshotBlobs(): ScreenshotBlobsRequestBuilder;
    /**
     * The search property
     */
    get search(): SearchRequestBuilder;
    /**
     * The sessions property
     */
    get sessions(): SessionsRequestBuilder;
    /**
     * The storageStates property
     */
    get storageStates(): StorageStatesRequestBuilder;
    /**
     * The webhooks property
     */
    get webhooks(): WebhooksRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const V1RequestBuilderUriTemplate = "{+baseurl}/v1";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const V1RequestBuilderNavigationMetadata: Record<Exclude<keyof V1RequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    cdp: {
        navigationMetadata: CdpRequestBuilderNavigationMetadata,
    },
    crawl: {
        navigationMetadata: CrawlRequestBuilderNavigationMetadata,
    },
    crawlRuns: {
        requestsMetadata: CrawlRunsRequestBuilderRequestsMetadata,
        navigationMetadata: CrawlRunsRequestBuilderNavigationMetadata,
    },
    datasets: {
        requestsMetadata: DatasetsRequestBuilderRequestsMetadata,
        navigationMetadata: DatasetsRequestBuilderNavigationMetadata,
    },
    extract: {
        requestsMetadata: ExtractRequestBuilderRequestsMetadata,
    },
    kv: {
        navigationMetadata: KvRequestBuilderNavigationMetadata,
    },
    map: {
        requestsMetadata: MapRequestBuilderRequestsMetadata,
    },
    page: {
        navigationMetadata: PageRequestBuilderNavigationMetadata,
    },
    profiles: {
        requestsMetadata: ProfilesRequestBuilderRequestsMetadata,
        navigationMetadata: ProfilesRequestBuilderNavigationMetadata,
    },
    proxyProviders: {
        requestsMetadata: ProxyProvidersRequestBuilderRequestsMetadata,
    },
    recordings: {
        requestsMetadata: RecordingsRequestBuilderRequestsMetadata,
        navigationMetadata: RecordingsRequestBuilderNavigationMetadata,
    },
    schedules: {
        requestsMetadata: SchedulesRequestBuilderRequestsMetadata,
        navigationMetadata: SchedulesRequestBuilderNavigationMetadata,
    },
    scrape: {
        requestsMetadata: ScrapeRequestBuilderRequestsMetadata,
        navigationMetadata: ScrapeRequestBuilderNavigationMetadata,
    },
    screenshotBlobs: {
        navigationMetadata: ScreenshotBlobsRequestBuilderNavigationMetadata,
    },
    search: {
        requestsMetadata: SearchRequestBuilderRequestsMetadata,
    },
    sessions: {
        requestsMetadata: SessionsRequestBuilderRequestsMetadata,
        navigationMetadata: SessionsRequestBuilderNavigationMetadata,
    },
    storageStates: {
        requestsMetadata: StorageStatesRequestBuilderRequestsMetadata,
        navigationMetadata: StorageStatesRequestBuilderNavigationMetadata,
    },
    webhooks: {
        requestsMetadata: WebhooksRequestBuilderRequestsMetadata,
        navigationMetadata: WebhooksRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
