/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithRefItemRequestBuilder, WithRefItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/screenshot-blobs
 */
export interface ScreenshotBlobsRequestBuilder extends BaseRequestBuilder<ScreenshotBlobsRequestBuilder> {
    /**
     * Gets an item from the ghostcrawl.v1.screenshotBlobs.item collection
     * @param ref Unique identifier of the item
     * @returns {WithRefItemRequestBuilder}
     */
     byRef(ref: string) : WithRefItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ScreenshotBlobsRequestBuilderUriTemplate = "{+baseurl}/v1/screenshot-blobs";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ScreenshotBlobsRequestBuilderNavigationMetadata: Record<Exclude<keyof ScreenshotBlobsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byRef: {
        requestsMetadata: WithRefItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["ref"],
    },
};
/* tslint:enable */
/* eslint-enable */
