/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHTTPValidationErrorFromDiscriminatorValue, serializeCookiesDeleteBody, serializeCookiesSetBody, type CookiesDeleteBody, type CookiesSetBody, type HTTPValidationError } from '../../../models/index.js';
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/page/cookies
 */
export interface CookiesRequestBuilder extends BaseRequestBuilder<CookiesRequestBuilder> {
    /**
     * Delete cookies
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UntypedNode>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     delete(body: CookiesDeleteBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UntypedNode | undefined>;
    /**
     * Get cookies
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UntypedNode>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     get(requestConfiguration?: RequestConfiguration<CookiesRequestBuilderGetQueryParameters> | undefined) : Promise<UntypedNode | undefined>;
    /**
     * Set cookies
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UntypedNode>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     post(body: CookiesSetBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UntypedNode | undefined>;
    /**
     * Delete cookies
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(body: CookiesDeleteBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Get cookies
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<CookiesRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Set cookies
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CookiesSetBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Get cookies
 */
export interface CookiesRequestBuilderGetQueryParameters {
    domain?: string;
    name?: string;
    profileId?: string;
}
/**
 * Uri template for the request builder.
 */
export const CookiesRequestBuilderUriTemplate = "{+baseurl}/v1/page/cookies{?domain*,name*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const CookiesRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "profileId": "profile_id",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const CookiesRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: CookiesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUntypedNodeFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCookiesDeleteBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
    get: {
        uriTemplate: "{+baseurl}/v1/page/cookies?profile_id={profile_id}{&domain*,name*}",
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUntypedNodeFromDiscriminatorValue,
        queryParametersMapper: CookiesRequestBuilderGetQueryParametersMapper,
    },
    post: {
        uriTemplate: CookiesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUntypedNodeFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCookiesSetBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
