/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHTTPValidationErrorFromDiscriminatorValue, type HTTPValidationError } from '../../models/index.js';
// @ts-ignore
import { DetachRequestBuilderRequestsMetadata, type DetachRequestBuilder } from './detach/index.js';
// @ts-ignore
import { type WithId_or_nameItemRequestBuilder, WithId_or_nameItemRequestBuilderNavigationMetadata, WithId_or_nameItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type AdditionalDataHolder, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter, type UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {StorageStatesPostRequestBody}
 */
// @ts-ignore
export function createStorageStatesPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoStorageStatesPostRequestBody;
}
/**
 * The deserialization information for the current model
 * @param StorageStatesPostRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoStorageStatesPostRequestBody(storageStatesPostRequestBody: Partial<StorageStatesPostRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param StorageStatesPostRequestBody The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeStorageStatesPostRequestBody(writer: SerializationWriter, storageStatesPostRequestBody: Partial<StorageStatesPostRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!storageStatesPostRequestBody || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(storageStatesPostRequestBody.additionalData);
}
export interface StorageStatesPostRequestBody extends AdditionalDataHolder, Parsable {
}
/**
 * Builds and executes requests for operations under /v1/storage-states
 */
export interface StorageStatesRequestBuilder extends BaseRequestBuilder<StorageStatesRequestBuilder> {
    /**
     * The detach property
     */
    get detach(): DetachRequestBuilder;
    /**
     * Gets an item from the ghostcrawl.v1.storageStates.item collection
     * @param id_or_name Unique identifier of the item
     * @returns {WithId_or_nameItemRequestBuilder}
     */
     byId_or_name(id_or_name: string) : WithId_or_nameItemRequestBuilder;
    /**
     * owner-scoped cursor pagination.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UntypedNode>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     get(requestConfiguration?: RequestConfiguration<StorageStatesRequestBuilderGetQueryParameters> | undefined) : Promise<UntypedNode | undefined>;
    /**
     * snapshot Playwright storage state + Fernet-encrypt. Must-haves:- scope gate: storage:write- body validated manually (to emit storage_state_name_invalid)- live page lookup: get_live_page(org_id, profile_id) → no_active_session on miss- encrypt: fernet_store.encrypt(json.dumps(state).encode)- 5MB cap: StorageStateTooLarge → storage_state_too_large envelope- save-vs-update: pre-upsert check → storage_state.saved vs.updated audit- returns StorageStateMetadata (NO blob_ciphertext; Pitfall 7)
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UntypedNode>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     post(body: StorageStatesPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UntypedNode | undefined>;
    /**
     * owner-scoped cursor pagination.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<StorageStatesRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * snapshot Playwright storage state + Fernet-encrypt. Must-haves:- scope gate: storage:write- body validated manually (to emit storage_state_name_invalid)- live page lookup: get_live_page(org_id, profile_id) → no_active_session on miss- encrypt: fernet_store.encrypt(json.dumps(state).encode)- 5MB cap: StorageStateTooLarge → storage_state_too_large envelope- save-vs-update: pre-upsert check → storage_state.saved vs.updated audit- returns StorageStateMetadata (NO blob_ciphertext; Pitfall 7)
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: StorageStatesPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * owner-scoped cursor pagination.
 */
export interface StorageStatesRequestBuilderGetQueryParameters {
    cursor?: string;
    limit?: number;
}
/**
 * Uri template for the request builder.
 */
export const StorageStatesRequestBuilderUriTemplate = "{+baseurl}/v1/storage-states{?cursor*,limit*}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const StorageStatesRequestBuilderNavigationMetadata: Record<Exclude<keyof StorageStatesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId_or_name: {
        requestsMetadata: WithId_or_nameItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithId_or_nameItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["id_or_name"],
    },
    detach: {
        requestsMetadata: DetachRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const StorageStatesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: StorageStatesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUntypedNodeFromDiscriminatorValue,
    },
    post: {
        uriTemplate: StorageStatesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUntypedNodeFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeStorageStatesPostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
