/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHTTPValidationErrorFromDiscriminatorValue, serializeScrapeRequest, type HTTPValidationError, type ScrapeRequest } from '../../models/index.js';
// @ts-ignore
import { BatchRequestBuilderRequestsMetadata, type BatchRequestBuilder } from './batch/index.js';
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/scrape
 */
export interface ScrapeRequestBuilder extends BaseRequestBuilder<ScrapeRequestBuilder> {
    /**
     * The batch property
     */
    get batch(): BatchRequestBuilder;
    /**
     * Bearer-gated scrape with identity field.
     * @param body POST /v1/scrape request body (identity-aware shape).
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UntypedNode>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     post(body: ScrapeRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UntypedNode | undefined>;
    /**
     * Bearer-gated scrape with identity field.
     * @param body POST /v1/scrape request body (identity-aware shape).
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ScrapeRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ScrapeRequestBuilderUriTemplate = "{+baseurl}/v1/scrape";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ScrapeRequestBuilderNavigationMetadata: Record<Exclude<keyof ScrapeRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    batch: {
        requestsMetadata: BatchRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ScrapeRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ScrapeRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUntypedNodeFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeScrapeRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
