/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHTTPValidationErrorFromDiscriminatorValue, createWebhookDeliveryListResponseFromDiscriminatorValue, type HTTPValidationError, type WebhookDeliveryListResponse } from '../../../../models/index.js';
// @ts-ignore
import { type WithDelivery_ItemRequestBuilder, WithDelivery_ItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/webhooks/{webhook_id}/deliveries
 */
export interface DeliveriesRequestBuilder extends BaseRequestBuilder<DeliveriesRequestBuilder> {
    /**
     * Gets an item from the ghostcrawl.v1.webhooks.item.deliveries.item collection
     * @param delivery_id Unique identifier of the item
     * @returns {WithDelivery_ItemRequestBuilder}
     */
     byDelivery_id(delivery_id: string) : WithDelivery_ItemRequestBuilder;
    /**
     * GET /v1/webhooks/{webhook_id}/deliveries.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<WebhookDeliveryListResponse>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     get(requestConfiguration?: RequestConfiguration<DeliveriesRequestBuilderGetQueryParameters> | undefined) : Promise<WebhookDeliveryListResponse | undefined>;
    /**
     * GET /v1/webhooks/{webhook_id}/deliveries.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<DeliveriesRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * GET /v1/webhooks/{webhook_id}/deliveries.
 */
export interface DeliveriesRequestBuilderGetQueryParameters {
    createdAtFrom?: string;
    createdAtTo?: string;
    cursor?: string;
    limit?: number;
    tags?: string;
}
/**
 * Uri template for the request builder.
 */
export const DeliveriesRequestBuilderUriTemplate = "{+baseurl}/v1/webhooks/{webhook_id}/deliveries{?created_at_from*,created_at_to*,cursor*,limit*,tags*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const DeliveriesRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "createdAtFrom": "created_at_from",
    "createdAtTo": "created_at_to",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const DeliveriesRequestBuilderNavigationMetadata: Record<Exclude<keyof DeliveriesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byDelivery_id: {
        navigationMetadata: WithDelivery_ItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["delivery_id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const DeliveriesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: DeliveriesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createWebhookDeliveryListResponseFromDiscriminatorValue,
        queryParametersMapper: DeliveriesRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
