/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHTTPValidationErrorFromDiscriminatorValue, createWebhookPublicFromDiscriminatorValue, type HTTPValidationError, type WebhookPublic } from '../../../models/index.js';
// @ts-ignore
import { DeliveriesRequestBuilderNavigationMetadata, DeliveriesRequestBuilderRequestsMetadata, type DeliveriesRequestBuilder } from './deliveries/index.js';
// @ts-ignore
import { RotateSecretRequestBuilderRequestsMetadata, type RotateSecretRequestBuilder } from './rotateSecret/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/webhooks/{webhook_id}
 */
export interface WithWebhook_ItemRequestBuilder extends BaseRequestBuilder<WithWebhook_ItemRequestBuilder> {
    /**
     * The deliveries property
     */
    get deliveries(): DeliveriesRequestBuilder;
    /**
     * The rotateSecret property
     */
    get rotateSecret(): RotateSecretRequestBuilder;
    /**
     * DELETE /v1/webhooks/{webhook_id}. secret keys deleted best-effort.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Secret: NOT returned.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<WebhookPublic>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<WebhookPublic | undefined>;
    /**
     * DELETE /v1/webhooks/{webhook_id}. secret keys deleted best-effort.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Secret: NOT returned.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithWebhook_ItemRequestBuilderUriTemplate = "{+baseurl}/v1/webhooks/{webhook_id}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithWebhook_ItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithWebhook_ItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    deliveries: {
        requestsMetadata: DeliveriesRequestBuilderRequestsMetadata,
        navigationMetadata: DeliveriesRequestBuilderNavigationMetadata,
    },
    rotateSecret: {
        requestsMetadata: RotateSecretRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithWebhook_ItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: WithWebhook_ItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
    },
    get: {
        uriTemplate: WithWebhook_ItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createWebhookPublicFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
