/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHTTPValidationErrorFromDiscriminatorValue, serializeStorageStateDetachRequest, type HTTPValidationError, type StorageStateDetachRequest } from '../../../models/index.js';
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/storage-states/detach
 */
export interface DetachRequestBuilder extends BaseRequestBuilder<DetachRequestBuilder> {
    /**
     * clear profile sticky-attach binding. detach is binding-only, NO storage_state audit row emitted. Returns 204.
     * @param body POST /v1/storage-states/detach, clear sticky-attach binding.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UntypedNode>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     post(body: StorageStateDetachRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UntypedNode | undefined>;
    /**
     * clear profile sticky-attach binding. detach is binding-only, NO storage_state audit row emitted. Returns 204.
     * @param body POST /v1/storage-states/detach, clear sticky-attach binding.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: StorageStateDetachRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const DetachRequestBuilderUriTemplate = "{+baseurl}/v1/storage-states/detach";
/**
 * Metadata for all the requests in the request builder.
 */
export const DetachRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: DetachRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUntypedNodeFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeStorageStateDetachRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
