#!/usr/bin/env node
// Prebuild: emit src/version.ts with the package version as a plain string
// constant. branded.ts consumes this instead of resolving package.json via
// `createRequire(import.meta.url)` — `import.meta` is a syntax error under the
// CommonJS build target (tsconfig.cjs.json), so a module-agnostic constant is
// the only way the dual ESM+CJS build compiles. Regenerated on every build so
// the version never drifts from package.json.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const pkgPath = join(here, '..', 'package.json');
const srcPath = join(here, '..', 'src', 'version.ts');

const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
const version = pkg.version ?? '0.0.0';

const banner = `// AUTO-GENERATED by scripts/gen-version.mjs — do not edit by hand.
// Mirrors package.json "version" so branded.ts can read it without
// module-system-specific resolution (import.meta / createRequire), keeping the
// dual ESM+CJS build green.
export const SDK_VERSION = ${JSON.stringify(version)};
`;

writeFileSync(srcPath, banner);
process.stdout.write(`gen-version: SDK_VERSION=${version}\n`);
