/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHTTPValidationErrorFromDiscriminatorValue, serializeAuthContext, type HTTPValidationError, type AuthContext } from '../../../../../models/index.js';
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/recordings/{recording_-id}/visual/start
 */
export interface StartRequestBuilder extends BaseRequestBuilder<StartRequestBuilder> {
    /**
     * Start a visual recording for a live session. Creates a session_recordings row. Returns 201 with the recording row id. Security gates (in order): 1. 2. 3. ownership gate: session ownership verified
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UntypedNode>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     post(body: AuthContext, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UntypedNode | undefined>;
    /**
     * Start a visual recording for a live session. Creates a session_recordings row. Returns 201 with the recording row id. Security gates (in order): 1. 2. 3. ownership gate: session ownership verified
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: AuthContext, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const StartRequestBuilderUriTemplate = "{+baseurl}/v1/recordings/{recording_%2Did}/visual/start";
/**
 * Metadata for all the requests in the request builder.
 */
export const StartRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: StartRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUntypedNodeFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeAuthContext,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
