/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHTTPValidationErrorFromDiscriminatorValue, type HTTPValidationError } from '../../../../models/index.js';
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/sessions/{profile_-id}/pin
 */
export interface PinRequestBuilder extends BaseRequestBuilder<PinRequestBuilder> {
    /**
     * mark the session/identity sticky (pinned). Reads session, verifies org ownership,then writes back `pinned=True` + `pinned_at=<epoch>` preserving the TTL.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UntypedNode>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UntypedNode | undefined>;
    /**
     * mark the session/identity sticky (pinned). Reads session, verifies org ownership,then writes back `pinned=True` + `pinned_at=<epoch>` preserving the TTL.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const PinRequestBuilderUriTemplate = "{+baseurl}/v1/sessions/{profile_%2Did}/pin";
/**
 * Metadata for all the requests in the request builder.
 */
export const PinRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: PinRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUntypedNodeFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
