from __future__ import annotations
from collections.abc import Callable
from dataclasses import dataclass, field
from kiota_abstractions.base_request_builder import BaseRequestBuilder
from kiota_abstractions.base_request_configuration import RequestConfiguration
from kiota_abstractions.default_query_parameters import QueryParameters
from kiota_abstractions.get_path_parameters import get_path_parameters
from kiota_abstractions.method import Method
from kiota_abstractions.request_adapter import RequestAdapter
from kiota_abstractions.request_information import RequestInformation
from kiota_abstractions.request_option import RequestOption
from kiota_abstractions.serialization import Parsable, ParsableFactory
from typing import Any, Optional, TYPE_CHECKING, Union
from warnings import warn

if TYPE_CHECKING:
    from .....models.problem_details import ProblemDetails
    from .....models.rotate_secret_response import RotateSecretResponse

class RotateSecretRequestBuilder(BaseRequestBuilder):
    """
    Builds and executes requests for operations under /v1/webhooks/{webhook_id}/rotate-secret
    """
    def __init__(self,request_adapter: RequestAdapter, path_parameters: Union[str, dict[str, Any]]) -> None:
        """
        Instantiates a new RotateSecretRequestBuilder and sets the default values.
        param path_parameters: The raw url or the url-template parameters for the request.
        param request_adapter: The request adapter to use to execute the requests.
        Returns: None
        """
        super().__init__(request_adapter, "{+baseurl}/v1/webhooks/{webhook_id}/rotate-secret", path_parameters)
    
    async def post(self,request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> Optional[RotateSecretResponse]:
        """
        POST /v1/webhooks/{webhook_id}/rotate-secret. Generate a new signing secret for the webhook. The previous secret remains valid for a short grace period so in-flight deliveries can still be verified.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: Optional[RotateSecretResponse]
        """
        request_info = self.to_post_request_information(
            request_configuration
        )
        from .....models.problem_details import ProblemDetails

        error_mapping: dict[str, type[ParsableFactory]] = {
            "422": ProblemDetails,
        }
        if not self.request_adapter:
            raise Exception("Http core is null") 
        from .....models.rotate_secret_response import RotateSecretResponse

        return await self.request_adapter.send_async(request_info, RotateSecretResponse, error_mapping)
    
    def to_post_request_information(self,request_configuration: Optional[RequestConfiguration[QueryParameters]] = None) -> RequestInformation:
        """
        POST /v1/webhooks/{webhook_id}/rotate-secret. Generate a new signing secret for the webhook. The previous secret remains valid for a short grace period so in-flight deliveries can still be verified.
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: RequestInformation
        """
        request_info = RequestInformation(Method.POST, self.url_template, self.path_parameters)
        request_info.configure(request_configuration)
        request_info.headers.try_add("Accept", "application/json")
        return request_info
    
    def with_url(self,raw_url: str) -> RotateSecretRequestBuilder:
        """
        Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        param raw_url: The raw URL to use for the request builder.
        Returns: RotateSecretRequestBuilder
        """
        if raw_url is None:
            raise TypeError("raw_url cannot be null.")
        return RotateSecretRequestBuilder(self.request_adapter, raw_url)
    
    @dataclass
    class RotateSecretRequestBuilderPostRequestConfiguration(RequestConfiguration[QueryParameters]):
        """
        Configuration for the request such as headers, query parameters, and middleware options.
        """
        warn("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.", DeprecationWarning)
    

