/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CookiesRequestBuilderRequestsMetadata, type CookiesRequestBuilder } from './cookies/index.js';
// @ts-ignore
import { Dom_snapshotRequestBuilderRequestsMetadata, type Dom_snapshotRequestBuilder } from './dom_snapshot/index.js';
// @ts-ignore
import { DownloadRequestBuilderRequestsMetadata, type DownloadRequestBuilder } from './download/index.js';
// @ts-ignore
import { EvalRequestBuilderRequestsMetadata, type EvalRequestBuilder } from './eval/index.js';
// @ts-ignore
import { HarRequestBuilderRequestsMetadata, type HarRequestBuilder } from './har/index.js';
// @ts-ignore
import { ScrollRequestBuilderRequestsMetadata, type ScrollRequestBuilder } from './scroll/index.js';
// @ts-ignore
import { type UploadRequestBuilder, UploadRequestBuilderRequestsMetadata } from './upload/index.js';
// @ts-ignore
import { type WaitRequestBuilder, WaitRequestBuilderRequestsMetadata } from './wait/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/page
 */
export interface PageRequestBuilder extends BaseRequestBuilder<PageRequestBuilder> {
    /**
     * The cookies property
     */
    get cookies(): CookiesRequestBuilder;
    /**
     * The dom_snapshot property
     */
    get dom_snapshot(): Dom_snapshotRequestBuilder;
    /**
     * The download property
     */
    get download(): DownloadRequestBuilder;
    /**
     * The eval property
     */
    get eval(): EvalRequestBuilder;
    /**
     * The har property
     */
    get har(): HarRequestBuilder;
    /**
     * The scroll property
     */
    get scroll(): ScrollRequestBuilder;
    /**
     * The upload property
     */
    get upload(): UploadRequestBuilder;
    /**
     * The wait property
     */
    get wait(): WaitRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const PageRequestBuilderUriTemplate = "{+baseurl}/v1/page";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PageRequestBuilderNavigationMetadata: Record<Exclude<keyof PageRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    cookies: {
        requestsMetadata: CookiesRequestBuilderRequestsMetadata,
    },
    dom_snapshot: {
        requestsMetadata: Dom_snapshotRequestBuilderRequestsMetadata,
    },
    download: {
        requestsMetadata: DownloadRequestBuilderRequestsMetadata,
    },
    eval: {
        requestsMetadata: EvalRequestBuilderRequestsMetadata,
    },
    har: {
        requestsMetadata: HarRequestBuilderRequestsMetadata,
    },
    scroll: {
        requestsMetadata: ScrollRequestBuilderRequestsMetadata,
    },
    upload: {
        requestsMetadata: UploadRequestBuilderRequestsMetadata,
    },
    wait: {
        requestsMetadata: WaitRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
