/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHTTPValidationErrorFromDiscriminatorValue, type HTTPValidationError } from '../../models/index.js';
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/proxy-providers
 */
export interface ProxyProvidersRequestBuilder extends BaseRequestBuilder<ProxyProvidersRequestBuilder> {
    /**
     * curated proxy provider list. Bearer-gated. Returns the operator-curated list of proxyproviders with referral URLs (carrying the operator's creator code) andpricing summaries. The customer signs up here, pays the provider, and bringsthe creds. Security:, referral URLs are not secrets, but the customer-facing list is bearer-gated (a 140. 4-era extract-method refactor accidentallypromoted the unauthenticated renderer to the route + orphaned this gated handler;restored 2026-06-11).
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UntypedNode>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UntypedNode | undefined>;
    /**
     * curated proxy provider list. Bearer-gated. Returns the operator-curated list of proxyproviders with referral URLs (carrying the operator's creator code) andpricing summaries. The customer signs up here, pays the provider, and bringsthe creds. Security:, referral URLs are not secrets, but the customer-facing list is bearer-gated (a 140. 4-era extract-method refactor accidentallypromoted the unauthenticated renderer to the route + orphaned this gated handler;restored 2026-06-11).
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ProxyProvidersRequestBuilderUriTemplate = "{+baseurl}/v1/proxy-providers";
/**
 * Metadata for all the requests in the request builder.
 */
export const ProxyProvidersRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ProxyProvidersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUntypedNodeFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
