/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { RetryRequestBuilderRequestsMetadata, type RetryRequestBuilder } from './retry/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/webhooks/{webhook_id}/deliveries/{delivery_id}
 */
export interface WithDelivery_ItemRequestBuilder extends BaseRequestBuilder<WithDelivery_ItemRequestBuilder> {
    /**
     * The retry property
     */
    get retry(): RetryRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithDelivery_ItemRequestBuilderUriTemplate = "{+baseurl}/v1/webhooks/{webhook_id}/deliveries/{delivery_id}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithDelivery_ItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithDelivery_ItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    retry: {
        requestsMetadata: RetryRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
