/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHTTPValidationErrorFromDiscriminatorValue, serializeAuthContext, type HTTPValidationError, type AuthContext } from '../../../../models/index.js';
// @ts-ignore
import { FramesRequestBuilderRequestsMetadata, type FramesRequestBuilder } from './frames/index.js';
// @ts-ignore
import { StartRequestBuilderRequestsMetadata, type StartRequestBuilder } from './start/index.js';
// @ts-ignore
import { StopRequestBuilderRequestsMetadata, type StopRequestBuilder } from './stop/index.js';
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/recordings/{recording_-id}/visual
 */
export interface VisualRequestBuilder extends BaseRequestBuilder<VisualRequestBuilder> {
    /**
     * The frames property
     */
    get frames(): FramesRequestBuilder;
    /**
     * The start property
     */
    get start(): StartRequestBuilder;
    /**
     * The stop property
     */
    get stop(): StopRequestBuilder;
    /**
     * Get the HLS-style manifest pointer for a visual recording. Returns 200 {manifest_url, frame_count, status, engine} or 404 for
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UntypedNode>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     get(body: AuthContext, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UntypedNode | undefined>;
    /**
     * Get the HLS-style manifest pointer for a visual recording. Returns 200 {manifest_url, frame_count, status, engine} or 404 for
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(body: AuthContext, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const VisualRequestBuilderUriTemplate = "{+baseurl}/v1/recordings/{recording_%2Did}/visual";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const VisualRequestBuilderNavigationMetadata: Record<Exclude<keyof VisualRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    frames: {
        requestsMetadata: FramesRequestBuilderRequestsMetadata,
    },
    start: {
        requestsMetadata: StartRequestBuilderRequestsMetadata,
    },
    stop: {
        requestsMetadata: StopRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const VisualRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: VisualRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUntypedNodeFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeAuthContext,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
