/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { FrameRequestBuilderRequestsMetadata, type FrameRequestBuilder } from './frame/index.js';
// @ts-ignore
import { type UrlRequestBuilder, UrlRequestBuilderRequestsMetadata } from './url/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/cdp
 */
export interface CdpRequestBuilder extends BaseRequestBuilder<CdpRequestBuilder> {
    /**
     * The frame property
     */
    get frame(): FrameRequestBuilder;
    /**
     * The url property
     */
    get url(): UrlRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const CdpRequestBuilderUriTemplate = "{+baseurl}/v1/cdp";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CdpRequestBuilderNavigationMetadata: Record<Exclude<keyof CdpRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    frame: {
        requestsMetadata: FrameRequestBuilderRequestsMetadata,
    },
    url: {
        requestsMetadata: UrlRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
