/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHTTPValidationErrorFromDiscriminatorValue, serializeScheduleCreateRequest, type HTTPValidationError, type ScheduleCreateRequest } from '../../models/index.js';
// @ts-ignore
import { type WithSchedule_ItemRequestBuilder, WithSchedule_ItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/schedules
 */
export interface SchedulesRequestBuilder extends BaseRequestBuilder<SchedulesRequestBuilder> {
    /**
     * Gets an item from the ghostcrawl.v1.schedules.item collection
     * @param schedule_id Unique identifier of the item
     * @returns {WithSchedule_ItemRequestBuilder}
     */
     bySchedule_id(schedule_id: string) : WithSchedule_ItemRequestBuilder;
    /**
     * list.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UntypedNode>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UntypedNode | undefined>;
    /**
     * create a cron-triggered scrape/crawl schedule. Validations: cron_expr must parse (422 invalid_cron) job_type must be 'scrape', 'crawl', or 'change_monitor' (422 invalid_job_type) notify_webhook must be SSRF-safe HTTPS URL if provided (422 invalid_webhook) per-org count < cap (429 schedule_cap_reached) unique name per org (409 schedule_exists)
     * @param body POST /v1/schedules body.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UntypedNode>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     post(body: ScheduleCreateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UntypedNode | undefined>;
    /**
     * list.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * create a cron-triggered scrape/crawl schedule. Validations: cron_expr must parse (422 invalid_cron) job_type must be 'scrape', 'crawl', or 'change_monitor' (422 invalid_job_type) notify_webhook must be SSRF-safe HTTPS URL if provided (422 invalid_webhook) per-org count < cap (429 schedule_cap_reached) unique name per org (409 schedule_exists)
     * @param body POST /v1/schedules body.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ScheduleCreateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SchedulesRequestBuilderUriTemplate = "{+baseurl}/v1/schedules";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SchedulesRequestBuilderNavigationMetadata: Record<Exclude<keyof SchedulesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    bySchedule_id: {
        requestsMetadata: WithSchedule_ItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["schedule_id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const SchedulesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: SchedulesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUntypedNodeFromDiscriminatorValue,
    },
    post: {
        uriTemplate: SchedulesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUntypedNodeFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeScheduleCreateRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
