/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHTTPValidationErrorFromDiscriminatorValue, serializeHarBody, type HarBody, type HTTPValidationError } from '../../../models/index.js';
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/page/har
 */
export interface HarRequestBuilder extends BaseRequestBuilder<HarRequestBuilder> {
    /**
     * Return the HAR-equivalent JSON for the live session. Reads from the sidecar's per-session network ring (productionwiring) or via context.har_export when the BrowserContext was launchedwith ``record_har_path``. Over-cap (>5 MB) returns a truncation flagrather than an error envelope, per
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UntypedNode>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     post(body: HarBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UntypedNode | undefined>;
    /**
     * Return the HAR-equivalent JSON for the live session. Reads from the sidecar's per-session network ring (productionwiring) or via context.har_export when the BrowserContext was launchedwith ``record_har_path``. Over-cap (>5 MB) returns a truncation flagrather than an error envelope, per
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: HarBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const HarRequestBuilderUriTemplate = "{+baseurl}/v1/page/har";
/**
 * Metadata for all the requests in the request builder.
 */
export const HarRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: HarRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUntypedNodeFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeHarBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
