/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHTTPValidationErrorFromDiscriminatorValue, serializeProfileCreateRequest, type HTTPValidationError, type ProfileCreateRequest } from '../../models/index.js';
// @ts-ignore
import { type WithNameItemRequestBuilder, WithNameItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/profiles
 */
export interface ProfilesRequestBuilder extends BaseRequestBuilder<ProfilesRequestBuilder> {
    /**
     * Gets an item from the ghostcrawl.v1.profiles.item collection
     * @param name Unique identifier of the item
     * @returns {WithNameItemRequestBuilder}
     */
     byName(name: string) : WithNameItemRequestBuilder;
    /**
     * cursor pagination. new endpoint. silently created_at_from > created_at_to → 400 (not 422).
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UntypedNode>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     get(requestConfiguration?: RequestConfiguration<ProfilesRequestBuilderGetQueryParameters> | undefined) : Promise<UntypedNode | undefined>;
    /**
     * mint a durable {org, name} → identity binding. 409 on duplicate name; 422 on invalid identity_spec.
     * @param body POST /v1/profiles body, create a named persistent profile.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UntypedNode>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     post(body: ProfileCreateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UntypedNode | undefined>;
    /**
     * cursor pagination. new endpoint. silently created_at_from > created_at_to → 400 (not 422).
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<ProfilesRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * mint a durable {org, name} → identity binding. 409 on duplicate name; 422 on invalid identity_spec.
     * @param body POST /v1/profiles body, create a named persistent profile.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ProfileCreateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * cursor pagination. new endpoint. silently created_at_from > created_at_to → 400 (not 422).
 */
export interface ProfilesRequestBuilderGetQueryParameters {
    createdAtFrom?: string;
    createdAtTo?: string;
    cursor?: string;
    limit?: number;
    tags?: string;
}
/**
 * Uri template for the request builder.
 */
export const ProfilesRequestBuilderUriTemplate = "{+baseurl}/v1/profiles{?created_at_from*,created_at_to*,cursor*,limit*,tags*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const ProfilesRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "createdAtFrom": "created_at_from",
    "createdAtTo": "created_at_to",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ProfilesRequestBuilderNavigationMetadata: Record<Exclude<keyof ProfilesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byName: {
        requestsMetadata: WithNameItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["name"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ProfilesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ProfilesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUntypedNodeFromDiscriminatorValue,
        queryParametersMapper: ProfilesRequestBuilderGetQueryParametersMapper,
    },
    post: {
        uriTemplate: ProfilesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUntypedNodeFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeProfileCreateRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
