/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHTTPValidationErrorFromDiscriminatorValue, type HTTPValidationError } from '../../../../../models/index.js';
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/sessions/{profile_-id}/recording/start
 */
export interface StartRequestBuilder extends BaseRequestBuilder<StartRequestBuilder> {
    /**
     * recordings:write. Tier: interaction (recording_enabled on org). Returns 201 RecordingResponse; emits recording.started audit.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UntypedNode>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UntypedNode | undefined>;
    /**
     * recordings:write. Tier: interaction (recording_enabled on org). Returns 201 RecordingResponse; emits recording.started audit.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const StartRequestBuilderUriTemplate = "{+baseurl}/v1/sessions/{profile_%2Did}/recording/start";
/**
 * Metadata for all the requests in the request builder.
 */
export const StartRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: StartRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUntypedNodeFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
