/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHTTPValidationErrorFromDiscriminatorValue, type HTTPValidationError } from '../../../models/index.js';
// @ts-ignore
import { type VisualRequestBuilder, VisualRequestBuilderNavigationMetadata, VisualRequestBuilderRequestsMetadata } from './visual/index.js';
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/recordings/{recording_-id}
 */
export interface Recording_ItemRequestBuilder extends BaseRequestBuilder<Recording_ItemRequestBuilder> {
    /**
     * The visual property
     */
    get visual(): VisualRequestBuilder;
    /**
     * DELETE /v1/recordings/{recording_id}.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     *
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UntypedNode>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UntypedNode | undefined>;
    /**
     * DELETE /v1/recordings/{recording_id}.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     *
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const Recording_ItemRequestBuilderUriTemplate = "{+baseurl}/v1/recordings/{recording_%2Did}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const Recording_ItemRequestBuilderNavigationMetadata: Record<Exclude<keyof Recording_ItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    visual: {
        requestsMetadata: VisualRequestBuilderRequestsMetadata,
        navigationMetadata: VisualRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const Recording_ItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: Recording_ItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
    },
    get: {
        uriTemplate: Recording_ItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUntypedNodeFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
