/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHTTPValidationErrorFromDiscriminatorValue, serializeDomSnapshotBody, type DomSnapshotBody, type HTTPValidationError } from '../../../models/index.js';
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/page/dom_snapshot
 */
export interface Dom_snapshotRequestBuilder extends BaseRequestBuilder<Dom_snapshotRequestBuilder> {
    /**
     * Return ``page.content`` for the live session, capped at 5 MB. callers retry with finer scope or fall back to /v1/page/eval for selector-rooted extraction.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UntypedNode>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     post(body: DomSnapshotBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UntypedNode | undefined>;
    /**
     * Return ``page.content`` for the live session, capped at 5 MB. callers retry with finer scope or fall back to /v1/page/eval for selector-rooted extraction.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: DomSnapshotBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const Dom_snapshotRequestBuilderUriTemplate = "{+baseurl}/v1/page/dom_snapshot";
/**
 * Metadata for all the requests in the request builder.
 */
export const Dom_snapshotRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: Dom_snapshotRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUntypedNodeFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeDomSnapshotBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
