/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHTTPValidationErrorFromDiscriminatorValue, type HTTPValidationError } from '../../../../models/index.js';
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/sessions/{profile_-id}/budget-stream
 */
export interface BudgetStreamRequestBuilder extends BaseRequestBuilder<BudgetStreamRequestBuilder> {
    /**
     * SSE stream of live budget counters for a session. Emits data: events only on counter change (250ms poll). Heartbeat every 15s (override via PHASE91_SSE_HEARTBEAT_INTERVAL env var for tests). Closes on: tombstone flag | client disconnect | server shutdown. Proxy anti-buffer headers: Cache-Control: no-cache, X-Accel-Buffering: no,Connection: keep-alive. Auth: budgets:read for own session. connection: pipeline-per-iteration → connection returns to pool after eachpipe.execute. No connection held across asyncio.sleep boundary (Pitfall 2). Decision traceability:; Pitfalls 2/7.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UntypedNode>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UntypedNode | undefined>;
    /**
     * SSE stream of live budget counters for a session. Emits data: events only on counter change (250ms poll). Heartbeat every 15s (override via PHASE91_SSE_HEARTBEAT_INTERVAL env var for tests). Closes on: tombstone flag | client disconnect | server shutdown. Proxy anti-buffer headers: Cache-Control: no-cache, X-Accel-Buffering: no,Connection: keep-alive. Auth: budgets:read for own session. connection: pipeline-per-iteration → connection returns to pool after eachpipe.execute. No connection held across asyncio.sleep boundary (Pitfall 2). Decision traceability:; Pitfalls 2/7.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const BudgetStreamRequestBuilderUriTemplate = "{+baseurl}/v1/sessions/{profile_%2Did}/budget-stream";
/**
 * Metadata for all the requests in the request builder.
 */
export const BudgetStreamRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: BudgetStreamRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUntypedNodeFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
