/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHTTPValidationErrorFromDiscriminatorValue, serializeStorageStateAttachRequest, type HTTPValidationError, type StorageStateAttachRequest } from '../../../../models/index.js';
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/storage-states/{id_or_name}/attach
 */
export interface AttachRequestBuilder extends BaseRequestBuilder<AttachRequestBuilder> {
    /**
     * attach a storage state to a profile. Decrypts and validates the named storage state, filters expired cookies, then sets the sticky binding so subsequent sessions on this profile start with the saved state loaded. Corrupted data → storage_state_decrypt_failed (400).
     * @param body POST /v1/storage-states/{id_or_name}/attach, sticky-attach to a profile.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UntypedNode>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     post(body: StorageStateAttachRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UntypedNode | undefined>;
    /**
     * attach a storage state to a profile. Decrypts and validates the named storage state, filters expired cookies, then sets the sticky binding so subsequent sessions on this profile start with the saved state loaded. Corrupted data → storage_state_decrypt_failed (400).
     * @param body POST /v1/storage-states/{id_or_name}/attach, sticky-attach to a profile.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: StorageStateAttachRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const AttachRequestBuilderUriTemplate = "{+baseurl}/v1/storage-states/{id_or_name}/attach";
/**
 * Metadata for all the requests in the request builder.
 */
export const AttachRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: AttachRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUntypedNodeFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeStorageStateAttachRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
