/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHTTPValidationErrorFromDiscriminatorValue, serializeAuthContext, type HTTPValidationError, type AuthContext } from '../../../../../models/index.js';
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/recordings/{recording_-id}/visual/frames
 */
export interface FramesRequestBuilder extends BaseRequestBuilder<FramesRequestBuilder> {
    /**
     * List paginated frame references for frame-by-frame replay. next_cursor == -1 means no more pages.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UntypedNode>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     get(body: AuthContext, requestConfiguration?: RequestConfiguration<FramesRequestBuilderGetQueryParameters> | undefined) : Promise<UntypedNode | undefined>;
    /**
     * List paginated frame references for frame-by-frame replay. next_cursor == -1 means no more pages.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(body: AuthContext, requestConfiguration?: RequestConfiguration<FramesRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * List paginated frame references for frame-by-frame replay. next_cursor == -1 means no more pages.
 */
export interface FramesRequestBuilderGetQueryParameters {
    /**
     * Start frame index (cursor-paginated)
     */
    cursor?: number;
    /**
     * Max frames per page
     */
    limit?: number;
}
/**
 * Uri template for the request builder.
 */
export const FramesRequestBuilderUriTemplate = "{+baseurl}/v1/recordings/{recording_%2Did}/visual/frames{?cursor*,limit*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const FramesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: FramesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUntypedNodeFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeAuthContext,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
