/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHTTPValidationErrorFromDiscriminatorValue, type HTTPValidationError } from '../../models/index.js';
// @ts-ignore
import { Recording_ItemRequestBuilderNavigationMetadata, Recording_ItemRequestBuilderRequestsMetadata, type Recording_ItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/recordings
 */
export interface RecordingsRequestBuilder extends BaseRequestBuilder<RecordingsRequestBuilder> {
    /**
     * Gets an item from the ghostcrawl.v1.recordings.item collection
     * @param recording_Id Unique identifier of the item
     * @returns {Recording_ItemRequestBuilder}
     */
     byRecording_Id(recording_Id: string) : Recording_ItemRequestBuilder;
    /**
     * cursor pagination. items[*] shape unchanged. created_at_from > created_at_to → 400 (not 422).
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UntypedNode>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     get(requestConfiguration?: RequestConfiguration<RecordingsRequestBuilderGetQueryParameters> | undefined) : Promise<UntypedNode | undefined>;
    /**
     * cursor pagination. items[*] shape unchanged. created_at_from > created_at_to → 400 (not 422).
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<RecordingsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * cursor pagination. items[*] shape unchanged. created_at_from > created_at_to → 400 (not 422).
 */
export interface RecordingsRequestBuilderGetQueryParameters {
    createdAtFrom?: string;
    createdAtTo?: string;
    cursor?: string;
    limit?: number;
    tags?: string;
}
/**
 * Uri template for the request builder.
 */
export const RecordingsRequestBuilderUriTemplate = "{+baseurl}/v1/recordings{?created_at_from*,created_at_to*,cursor*,limit*,tags*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const RecordingsRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "createdAtFrom": "created_at_from",
    "createdAtTo": "created_at_to",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const RecordingsRequestBuilderNavigationMetadata: Record<Exclude<keyof RecordingsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byRecording_Id: {
        requestsMetadata: Recording_ItemRequestBuilderRequestsMetadata,
        navigationMetadata: Recording_ItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["recording_%2Did"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const RecordingsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: RecordingsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUntypedNodeFromDiscriminatorValue,
        queryParametersMapper: RecordingsRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
