/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithKeyItemRequestBuilder, WithKeyItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/kv
 */
export interface KvRequestBuilder extends BaseRequestBuilder<KvRequestBuilder> {
    /**
     * Gets an item from the ghostcrawl.v1.kv.item collection
     * @param key Unique identifier of the item
     * @returns {WithKeyItemRequestBuilder}
     */
     byKey(key: string) : WithKeyItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const KvRequestBuilderUriTemplate = "{+baseurl}/v1/kv";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const KvRequestBuilderNavigationMetadata: Record<Exclude<keyof KvRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byKey: {
        requestsMetadata: WithKeyItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["key"],
    },
};
/* tslint:enable */
/* eslint-enable */
