/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHTTPValidationErrorFromDiscriminatorValue, createMapResponseFromDiscriminatorValue, serializeMapBody, serializeMapResponse, type HTTPValidationError, type MapBody, type MapResponse } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/map
 */
export interface MapRequestBuilder extends BaseRequestBuilder<MapRequestBuilder> {
    /**
     * sitemap URL discovery. 1. The seed URL is validated against private/loopback/metadata targets. 2. The request is quota-checked. 3. URLs are discovered from the site's sitemaps. 4. Results are filtered to the same registrable domain by default. 5. An optional case-insensitive substring filter is applied to URLs. 6. Results are capped at 10000 regardless of the requested limit.
     * @param body Firecrawl-compatible /v1/map request body.camelCase field names per Firecrawl spec (noqa: N815 silences pydanticnaming convention warnings for intentional camelCase).
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MapResponse>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     post(body: MapBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MapResponse | undefined>;
    /**
     * sitemap URL discovery. 1. The seed URL is validated against private/loopback/metadata targets. 2. The request is quota-checked. 3. URLs are discovered from the site's sitemaps. 4. Results are filtered to the same registrable domain by default. 5. An optional case-insensitive substring filter is applied to URLs. 6. Results are capped at 10000 regardless of the requested limit.
     * @param body Firecrawl-compatible /v1/map request body.camelCase field names per Firecrawl spec (noqa: N815 silences pydanticnaming convention warnings for intentional camelCase).
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: MapBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const MapRequestBuilderUriTemplate = "{+baseurl}/v1/map";
/**
 * Metadata for all the requests in the request builder.
 */
export const MapRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: MapRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createMapResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeMapBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
