/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHTTPValidationErrorFromDiscriminatorValue, serializeBatchScrapeRequest, type BatchScrapeRequest, type HTTPValidationError } from '../../../models/index.js';
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/scrape/batch
 */
export interface BatchRequestBuilder extends BaseRequestBuilder<BatchRequestBuilder> {
    /**
     * concurrent URL scrape (max 20 URLs, max concurrency 10). processes each URL with authentication.
     * @param body Request body for POST /v1/scrape/batch. Accepts 1–20 URLs and a concurrency cap 1–10. All other fields mirrorthe shared scrape params from ScrapeBody and are applied uniformly toevery URL in the batch.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UntypedNode>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     post(body: BatchScrapeRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UntypedNode | undefined>;
    /**
     * concurrent URL scrape (max 20 URLs, max concurrency 10). processes each URL with authentication.
     * @param body Request body for POST /v1/scrape/batch. Accepts 1–20 URLs and a concurrency cap 1–10. All other fields mirrorthe shared scrape params from ScrapeBody and are applied uniformly toevery URL in the batch.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: BatchScrapeRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const BatchRequestBuilderUriTemplate = "{+baseurl}/v1/scrape/batch";
/**
 * Metadata for all the requests in the request builder.
 */
export const BatchRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: BatchRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUntypedNodeFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeBatchScrapeRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
