/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHTTPValidationErrorFromDiscriminatorValue, createRotateSecretResponseFromDiscriminatorValue, type HTTPValidationError, type RotateSecretResponse } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/webhooks/{webhook_id}/rotate-secret
 */
export interface RotateSecretRequestBuilder extends BaseRequestBuilder<RotateSecretRequestBuilder> {
    /**
     * POST /v1/webhooks/{webhook_id}/rotate-secret. Generate a new signing secret for the webhook. The previous secret remains validfor a short grace period so in-flight deliveries can still be verified.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<RotateSecretResponse>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<RotateSecretResponse | undefined>;
    /**
     * POST /v1/webhooks/{webhook_id}/rotate-secret. Generate a new signing secret for the webhook. The previous secret remains validfor a short grace period so in-flight deliveries can still be verified.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const RotateSecretRequestBuilderUriTemplate = "{+baseurl}/v1/webhooks/{webhook_id}/rotate-secret";
/**
 * Metadata for all the requests in the request builder.
 */
export const RotateSecretRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: RotateSecretRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createRotateSecretResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
