/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHTTPValidationErrorFromDiscriminatorValue, createWebhookCreateResponseFromDiscriminatorValue, createWebhookListResponseFromDiscriminatorValue, serializeWebhookCreateRequest, serializeWebhookCreateResponse, type HTTPValidationError, type WebhookCreateRequest, type WebhookCreateResponse, type WebhookListResponse } from '../../models/index.js';
// @ts-ignore
import { type WithWebhook_ItemRequestBuilder, WithWebhook_ItemRequestBuilderNavigationMetadata, WithWebhook_ItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/webhooks
 */
export interface WebhooksRequestBuilder extends BaseRequestBuilder<WebhooksRequestBuilder> {
    /**
     * Gets an item from the ghostcrawl.v1.webhooks.item collection
     * @param webhook_id Unique identifier of the item
     * @returns {WithWebhook_ItemRequestBuilder}
     */
     byWebhook_id(webhook_id: string) : WithWebhook_ItemRequestBuilder;
    /**
     * cursor pagination. without it → 403.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<WebhookListResponse>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     get(requestConfiguration?: RequestConfiguration<WebhooksRequestBuilderGetQueryParameters> | undefined) : Promise<WebhookListResponse | undefined>;
    /**
     * Create a new webhook subscription. Returns the webhook plus the plaintext signing secret ONCE. Store the secret immediately, it cannot be recovered; only rotation via /rotate-secret provides a new one.
     * @param body Request body for POST /v1/webhooks.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<WebhookCreateResponse>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     post(body: WebhookCreateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<WebhookCreateResponse | undefined>;
    /**
     * cursor pagination. without it → 403.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<WebhooksRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Create a new webhook subscription. Returns the webhook plus the plaintext signing secret ONCE. Store the secret immediately, it cannot be recovered; only rotation via /rotate-secret provides a new one.
     * @param body Request body for POST /v1/webhooks.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: WebhookCreateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * cursor pagination. without it → 403.
 */
export interface WebhooksRequestBuilderGetQueryParameters {
    createdAtFrom?: string;
    createdAtTo?: string;
    cursor?: string;
    limit?: number;
    tags?: string;
}
/**
 * Uri template for the request builder.
 */
export const WebhooksRequestBuilderUriTemplate = "{+baseurl}/v1/webhooks{?created_at_from*,created_at_to*,cursor*,limit*,tags*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const WebhooksRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "createdAtFrom": "created_at_from",
    "createdAtTo": "created_at_to",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WebhooksRequestBuilderNavigationMetadata: Record<Exclude<keyof WebhooksRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byWebhook_id: {
        requestsMetadata: WithWebhook_ItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithWebhook_ItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["webhook_id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WebhooksRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WebhooksRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createWebhookListResponseFromDiscriminatorValue,
        queryParametersMapper: WebhooksRequestBuilderGetQueryParametersMapper,
    },
    post: {
        uriTemplate: WebhooksRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createWebhookCreateResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeWebhookCreateRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
