/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHTTPValidationErrorFromDiscriminatorValue, type HTTPValidationError } from '../../../models/index.js';
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/screenshot-blobs/{ref}
 */
export interface WithRefItemRequestBuilder extends BaseRequestBuilder<WithRefItemRequestBuilder> {
    /**
     * Fetch a screenshot blob by UUID ref, owner-scoped. Returns: 200 ``{ref, png_base64, page_url_host, created_at}`` on success. 404 ``{code: "not_found", message: "."}`` for missing ref OR enumeration of blobs belonging to other organisations.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UntypedNode>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UntypedNode | undefined>;
    /**
     * Fetch a screenshot blob by UUID ref, owner-scoped. Returns: 200 ``{ref, png_base64, page_url_host, created_at}`` on success. 404 ``{code: "not_found", message: "."}`` for missing ref OR enumeration of blobs belonging to other organisations.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithRefItemRequestBuilderUriTemplate = "{+baseurl}/v1/screenshot-blobs/{ref}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithRefItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithRefItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUntypedNodeFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
