/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { BudgetStreamRequestBuilderRequestsMetadata, type BudgetStreamRequestBuilder } from './budgetStream/index.js';
// @ts-ignore
import { ExtendRequestBuilderRequestsMetadata, type ExtendRequestBuilder } from './extend/index.js';
// @ts-ignore
import { PinRequestBuilderRequestsMetadata, type PinRequestBuilder } from './pin/index.js';
// @ts-ignore
import { RecordingRequestBuilderNavigationMetadata, type RecordingRequestBuilder } from './recording/index.js';
// @ts-ignore
import { ReleaseRequestBuilderRequestsMetadata, type ReleaseRequestBuilder } from './release/index.js';
// @ts-ignore
import { Takeover_releaseRequestBuilderRequestsMetadata, type Takeover_releaseRequestBuilder } from './takeover_release/index.js';
// @ts-ignore
import { Takeover_tokenRequestBuilderRequestsMetadata, type Takeover_tokenRequestBuilder } from './takeover_token/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/sessions/{profile_-id}
 */
export interface Profile_ItemRequestBuilder extends BaseRequestBuilder<Profile_ItemRequestBuilder> {
    /**
     * The budgetStream property
     */
    get budgetStream(): BudgetStreamRequestBuilder;
    /**
     * The extend property
     */
    get extend(): ExtendRequestBuilder;
    /**
     * The pin property
     */
    get pin(): PinRequestBuilder;
    /**
     * The recording property
     */
    get recording(): RecordingRequestBuilder;
    /**
     * The release property
     */
    get release(): ReleaseRequestBuilder;
    /**
     * The takeover_release property
     */
    get takeover_release(): Takeover_releaseRequestBuilder;
    /**
     * The takeover_token property
     */
    get takeover_token(): Takeover_tokenRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const Profile_ItemRequestBuilderUriTemplate = "{+baseurl}/v1/sessions/{profile_%2Did}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const Profile_ItemRequestBuilderNavigationMetadata: Record<Exclude<keyof Profile_ItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    budgetStream: {
        requestsMetadata: BudgetStreamRequestBuilderRequestsMetadata,
    },
    extend: {
        requestsMetadata: ExtendRequestBuilderRequestsMetadata,
    },
    pin: {
        requestsMetadata: PinRequestBuilderRequestsMetadata,
    },
    recording: {
        navigationMetadata: RecordingRequestBuilderNavigationMetadata,
    },
    release: {
        requestsMetadata: ReleaseRequestBuilderRequestsMetadata,
    },
    takeover_release: {
        requestsMetadata: Takeover_releaseRequestBuilderRequestsMetadata,
    },
    takeover_token: {
        requestsMetadata: Takeover_tokenRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
