/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHTTPValidationErrorFromDiscriminatorValue, serializeExtendBody, type ExtendBody, type HTTPValidationError } from '../../../../models/index.js';
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/sessions/{profile_-id}/extend
 */
export interface ExtendRequestBuilder extends BaseRequestBuilder<ExtendRequestBuilder> {
    /**
     * extend the session TTL. Reads session, verifies org ownership,then bumps the TTL by body.ttl_seconds (or a default extension).
     * @param body Body for POST /v1/sessions/{id}/extend.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UntypedNode>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     post(body: ExtendBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UntypedNode | undefined>;
    /**
     * extend the session TTL. Reads session, verifies org ownership,then bumps the TTL by body.ttl_seconds (or a default extension).
     * @param body Body for POST /v1/sessions/{id}/extend.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ExtendBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ExtendRequestBuilderUriTemplate = "{+baseurl}/v1/sessions/{profile_%2Did}/extend";
/**
 * Metadata for all the requests in the request builder.
 */
export const ExtendRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ExtendRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUntypedNodeFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeExtendBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
