/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHTTPValidationErrorFromDiscriminatorValue, createRetryDeliveryResponseFromDiscriminatorValue, type HTTPValidationError, type RetryDeliveryResponse } from '../../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/webhooks/{webhook_id}/deliveries/{delivery_id}/retry
 */
export interface RetryRequestBuilder extends BaseRequestBuilder<RetryRequestBuilder> {
    /**
     * POST /v1/webhooks/{webhook_id}/deliveries/{delivery_id}/retry. Re-enqueues the failed delivery with a fresh delivery_id; the original event_id is preserved so downstream consumers can detect the retry.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<RetryDeliveryResponse>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<RetryDeliveryResponse | undefined>;
    /**
     * POST /v1/webhooks/{webhook_id}/deliveries/{delivery_id}/retry. Re-enqueues the failed delivery with a fresh delivery_id; the original event_id is preserved so downstream consumers can detect the retry.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const RetryRequestBuilderUriTemplate = "{+baseurl}/v1/webhooks/{webhook_id}/deliveries/{delivery_id}/retry";
/**
 * Metadata for all the requests in the request builder.
 */
export const RetryRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: RetryRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createRetryDeliveryResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
