/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHTTPValidationErrorFromDiscriminatorValue, serializeExtractRequest, type ExtractRequest, type HTTPValidationError } from '../../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type BaseRequestBuilder, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ExtractPostResponse}
 */
// @ts-ignore
export function createExtractPostResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoExtractPostResponse;
}
/**
 * The deserialization information for the current model
 * @param ExtractPostResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoExtractPostResponse(extractPostResponse: Partial<ExtractPostResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
export interface ExtractPostResponse extends AdditionalDataHolder, Parsable {
}
/**
 * Builds and executes requests for operations under /v1/extract
 */
export interface ExtractRequestBuilder extends BaseRequestBuilder<ExtractRequestBuilder> {
    /**
     * structured extraction (deterministic default) + bring-your-own-model extraction. Two modes (selected by model_provider):DETERMINISTIC (model_provider absent, default): 1. The schema is validated (input guard). 2. The URL is validated against private/loopback/metadata targets. 3. The page is fetched and rendered. 4. Structured data is extracted via CSS/regex/keyword rules. 5. The result is validated against the schema, 422 on mismatch (field path only). Returns {"url","data","token_estimate"}. BRING-YOUR-OWN-MODEL (model_provider present): 1. Target URLs are resolved (urls or [url]). 2. The schema is validated if present. 3. At least one of prompt or schema is required, 400 prompt_or_schema_required otherwise. 4. Model credentials are validated, 400 invalid_model_provider on error (the message never echoes the key). 5. Every target URL is validated before fetching, 400 ssrf_blocked. 6. Each URL is fetched and converted to clean Markdown. 7. Your connected model performs the extraction. 8. With a schema present, the result is validated, 422 on mismatch. Returns {"urls","data","token_estimate"}. Security:- 401 without a valid Bearer token.- model_provider.api_key is request-scoped: never persisted, logged, or echoed.- Error responses never echo the schema body, fetched content, or credentials.
     * @param body POST /v1/extract request body, schema-driven extraction (deterministic) + bring-your-own-model extraction. Two extraction modes: - Deterministic (default, model_provider absent): CSS/regex/keyword extraction. Requires 'schema'. Returns {"url","data","token_estimate"}. - Bring-your-own-model (model_provider present): GhostCrawl fetches and prepares clean Markdown; your connected model performs the semantic extraction (you are not billed for model inference here, only the request quota). Returns {"urls","data","token_estimate"}. Security notes:- The 'schema' field is validated before any fetch (fail-fast input guard).- URLs are validated against private, loopback, and metadata targets before any fetch.- Error responses never echo the schema body, fetched content, or model credentials.- model_provider.api_key is request-scoped only: never persisted, logged, or returned in any response body or error message.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ExtractPostResponse>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     post(body: ExtractRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ExtractPostResponse | undefined>;
    /**
     * structured extraction (deterministic default) + bring-your-own-model extraction. Two modes (selected by model_provider):DETERMINISTIC (model_provider absent, default): 1. The schema is validated (input guard). 2. The URL is validated against private/loopback/metadata targets. 3. The page is fetched and rendered. 4. Structured data is extracted via CSS/regex/keyword rules. 5. The result is validated against the schema, 422 on mismatch (field path only). Returns {"url","data","token_estimate"}. BRING-YOUR-OWN-MODEL (model_provider present): 1. Target URLs are resolved (urls or [url]). 2. The schema is validated if present. 3. At least one of prompt or schema is required, 400 prompt_or_schema_required otherwise. 4. Model credentials are validated, 400 invalid_model_provider on error (the message never echoes the key). 5. Every target URL is validated before fetching, 400 ssrf_blocked. 6. Each URL is fetched and converted to clean Markdown. 7. Your connected model performs the extraction. 8. With a schema present, the result is validated, 422 on mismatch. Returns {"urls","data","token_estimate"}. Security:- 401 without a valid Bearer token.- model_provider.api_key is request-scoped: never persisted, logged, or echoed.- Error responses never echo the schema body, fetched content, or credentials.
     * @param body POST /v1/extract request body, schema-driven extraction (deterministic) + bring-your-own-model extraction. Two extraction modes: - Deterministic (default, model_provider absent): CSS/regex/keyword extraction. Requires 'schema'. Returns {"url","data","token_estimate"}. - Bring-your-own-model (model_provider present): GhostCrawl fetches and prepares clean Markdown; your connected model performs the semantic extraction (you are not billed for model inference here, only the request quota). Returns {"urls","data","token_estimate"}. Security notes:- The 'schema' field is validated before any fetch (fail-fast input guard).- URLs are validated against private, loopback, and metadata targets before any fetch.- Error responses never echo the schema body, fetched content, or model credentials.- model_provider.api_key is request-scoped only: never persisted, logged, or returned in any response body or error message.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ExtractRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Serializes information the current object
 * @param ExtractPostResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeExtractPostResponse(writer: SerializationWriter, extractPostResponse: Partial<ExtractPostResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!extractPostResponse || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(extractPostResponse.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const ExtractRequestBuilderUriTemplate = "{+baseurl}/v1/extract";
/**
 * Metadata for all the requests in the request builder.
 */
export const ExtractRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ExtractRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createExtractPostResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeExtractRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
