/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { StartRequestBuilderRequestsMetadata, type StartRequestBuilder } from './start/index.js';
// @ts-ignore
import { StopRequestBuilderRequestsMetadata, type StopRequestBuilder } from './stop/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/sessions/{profile_-id}/recording
 */
export interface RecordingRequestBuilder extends BaseRequestBuilder<RecordingRequestBuilder> {
    /**
     * The start property
     */
    get start(): StartRequestBuilder;
    /**
     * The stop property
     */
    get stop(): StopRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const RecordingRequestBuilderUriTemplate = "{+baseurl}/v1/sessions/{profile_%2Did}/recording";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const RecordingRequestBuilderNavigationMetadata: Record<Exclude<keyof RecordingRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    start: {
        requestsMetadata: StartRequestBuilderRequestsMetadata,
    },
    stop: {
        requestsMetadata: StopRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
