/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHTTPValidationErrorFromDiscriminatorValue, serializeDeepCrawlBody, type DeepCrawlBody, type HTTPValidationError } from '../../../models/index.js';
// @ts-ignore
import { type WithRun_ItemRequestBuilder, WithRun_ItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/crawl/deep
 */
export interface DeepRequestBuilder extends BaseRequestBuilder<DeepRequestBuilder> {
    /**
     * Gets an item from the ghostcrawl.v1.crawl.deep.item collection
     * @param run_id Unique identifier of the item
     * @returns {WithRun_ItemRequestBuilder}
     */
     byRun_id(run_id: string) : WithRun_ItemRequestBuilder;
    /**
     * queue an async deep crawl. Returns immediately with run_id and status="queued". Webhook fires on completion when webhook_url is provided. Auth: crawl:write scope required. Billing: crawl_pages_delta (Option A).
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UntypedNode>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     post(body: DeepCrawlBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UntypedNode | undefined>;
    /**
     * queue an async deep crawl. Returns immediately with run_id and status="queued". Webhook fires on completion when webhook_url is provided. Auth: crawl:write scope required. Billing: crawl_pages_delta (Option A).
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: DeepCrawlBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const DeepRequestBuilderUriTemplate = "{+baseurl}/v1/crawl/deep";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const DeepRequestBuilderNavigationMetadata: Record<Exclude<keyof DeepRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byRun_id: {
        requestsMetadata: WithRun_ItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["run_id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const DeepRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: DeepRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUntypedNodeFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeDeepCrawlBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
