from __future__ import annotations
from collections.abc import Callable
from dataclasses import dataclass, field
from kiota_abstractions.base_request_builder import BaseRequestBuilder
from kiota_abstractions.base_request_configuration import RequestConfiguration
from kiota_abstractions.default_query_parameters import QueryParameters
from kiota_abstractions.get_path_parameters import get_path_parameters
from kiota_abstractions.method import Method
from kiota_abstractions.request_adapter import RequestAdapter
from kiota_abstractions.request_information import RequestInformation
from kiota_abstractions.request_option import RequestOption
from kiota_abstractions.serialization import Parsable, ParsableFactory
from typing import Any, Optional, TYPE_CHECKING, Union
from warnings import warn

if TYPE_CHECKING:
    from ......models.auth_context import AuthContext
    from ......models.problem_details import ProblemDetails

class FramesRequestBuilder(BaseRequestBuilder):
    """
    Builds and executes requests for operations under /v1/recordings/{recording_-id}/visual/frames
    """
    def __init__(self,request_adapter: RequestAdapter, path_parameters: Union[str, dict[str, Any]]) -> None:
        """
        Instantiates a new FramesRequestBuilder and sets the default values.
        param path_parameters: The raw url or the url-template parameters for the request.
        param request_adapter: The request adapter to use to execute the requests.
        Returns: None
        """
        super().__init__(request_adapter, "{+baseurl}/v1/recordings/{recording_%2Did}/visual/frames{?cursor*,limit*}", path_parameters)
    
    async def get(self,body: AuthContext, request_configuration: Optional[RequestConfiguration[FramesRequestBuilderGetQueryParameters]] = None) -> Optional[bytes]:
        """
        List paginated frame references for frame-by-frame replay. next_cursor == -1 means no more pages.
        param body: The request body
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: bytes
        """
        if body is None:
            raise TypeError("body cannot be null.")
        request_info = self.to_get_request_information(
            body, request_configuration
        )
        from ......models.problem_details import ProblemDetails

        error_mapping: dict[str, type[ParsableFactory]] = {
            "422": ProblemDetails,
        }
        if not self.request_adapter:
            raise Exception("Http core is null") 
        return await self.request_adapter.send_primitive_async(request_info, "bytes", error_mapping)
    
    def to_get_request_information(self,body: AuthContext, request_configuration: Optional[RequestConfiguration[FramesRequestBuilderGetQueryParameters]] = None) -> RequestInformation:
        """
        List paginated frame references for frame-by-frame replay. next_cursor == -1 means no more pages.
        param body: The request body
        param request_configuration: Configuration for the request such as headers, query parameters, and middleware options.
        Returns: RequestInformation
        """
        if body is None:
            raise TypeError("body cannot be null.")
        request_info = RequestInformation(Method.GET, self.url_template, self.path_parameters)
        request_info.configure(request_configuration)
        request_info.headers.try_add("Accept", "application/json")
        request_info.set_content_from_parsable(self.request_adapter, "application/json", body)
        return request_info
    
    def with_url(self,raw_url: str) -> FramesRequestBuilder:
        """
        Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        param raw_url: The raw URL to use for the request builder.
        Returns: FramesRequestBuilder
        """
        if raw_url is None:
            raise TypeError("raw_url cannot be null.")
        return FramesRequestBuilder(self.request_adapter, raw_url)
    
    @dataclass
    class FramesRequestBuilderGetQueryParameters():
        """
        List paginated frame references for frame-by-frame replay. next_cursor == -1 means no more pages.
        """
        # Start frame index (cursor-paginated)
        cursor: Optional[int] = None

        # Max frames per page
        limit: Optional[int] = None

    
    @dataclass
    class FramesRequestBuilderGetRequestConfiguration(RequestConfiguration[FramesRequestBuilderGetQueryParameters]):
        """
        Configuration for the request such as headers, query parameters, and middleware options.
        """
        warn("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.", DeprecationWarning)
    

