/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { DeepRequestBuilderNavigationMetadata, DeepRequestBuilderRequestsMetadata, type DeepRequestBuilder } from './deep/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/crawl
 */
export interface CrawlRequestBuilder extends BaseRequestBuilder<CrawlRequestBuilder> {
    /**
     * The deep property
     */
    get deep(): DeepRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const CrawlRequestBuilderUriTemplate = "{+baseurl}/v1/crawl";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CrawlRequestBuilderNavigationMetadata: Record<Exclude<keyof CrawlRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    deep: {
        requestsMetadata: DeepRequestBuilderRequestsMetadata,
        navigationMetadata: DeepRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
