/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHTTPValidationErrorFromDiscriminatorValue, serializeCdpUrlRequest, type CdpUrlRequest, type HTTPValidationError } from '../../../models/index.js';
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type UntypedNode } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/cdp/url
 */
export interface UrlRequestBuilder extends BaseRequestBuilder<UrlRequestBuilder> {
    /**
     * Mint a short-TTL signed URL for cloud CDP access. Returns 200 {"url": "wss://.", "expires_in_seconds": 120} on success.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UntypedNode>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     post(body: CdpUrlRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UntypedNode | undefined>;
    /**
     * Mint a short-TTL signed URL for cloud CDP access. Returns 200 {"url": "wss://.", "expires_in_seconds": 120} on success.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CdpUrlRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const UrlRequestBuilderUriTemplate = "{+baseurl}/v1/cdp/url";
/**
 * Metadata for all the requests in the request builder.
 */
export const UrlRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: UrlRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUntypedNodeFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCdpUrlRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
