/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHTTPValidationErrorFromDiscriminatorValue, type HTTPValidationError } from '../../models/index.js';
// @ts-ignore
import { type WithRun_ItemRequestBuilder, WithRun_ItemRequestBuilderNavigationMetadata, WithRun_ItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { createUntypedNodeFromDiscriminatorValue, type AdditionalDataHolder, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type ParseNode, type RequestConfiguration, type RequestInformation, type RequestsMetadata, type SerializationWriter, type UntypedNode } from '@microsoft/kiota-abstractions';

export interface CrawlRunsPostRequestBody extends AdditionalDataHolder, Parsable {
}
/**
 * Builds and executes requests for operations under /v1/crawl-runs
 */
export interface CrawlRunsRequestBuilder extends BaseRequestBuilder<CrawlRunsRequestBuilder> {
    /**
     * Gets an item from the ghostcrawl.v1.crawlRuns.item collection
     * @param run_id Unique identifier of the item
     * @returns {WithRun_ItemRequestBuilder}
     */
     byRun_id(run_id: string) : WithRun_ItemRequestBuilder;
    /**
     * cursor pagination. {items, next_cursor, total_count}. change in; created_at_from > created_at_to → 400 (not 422). Error envelope for 403 unchanged (at error layer).
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UntypedNode>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     get(requestConfiguration?: RequestConfiguration<CrawlRunsRequestBuilderGetQueryParameters> | undefined) : Promise<UntypedNode | undefined>;
    /**
     * Start a crawl run
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UntypedNode>}
     * @throws {HTTPValidationError} error when the service returns a 422 status code
     */
     post(body: CrawlRunsPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UntypedNode | undefined>;
    /**
     * cursor pagination. {items, next_cursor, total_count}. change in; created_at_from > created_at_to → 400 (not 422). Error envelope for 403 unchanged (at error layer).
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<CrawlRunsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Start a crawl run
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CrawlRunsPostRequestBody, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * cursor pagination. {items, next_cursor, total_count}. change in; created_at_from > created_at_to → 400 (not 422). Error envelope for 403 unchanged (at error layer).
 */
export interface CrawlRunsRequestBuilderGetQueryParameters {
    createdAtFrom?: string;
    createdAtTo?: string;
    cursor?: string;
    limit?: number;
    tags?: string;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CrawlRunsPostRequestBody}
 */
// @ts-ignore
export function createCrawlRunsPostRequestBodyFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCrawlRunsPostRequestBody;
}
/**
 * The deserialization information for the current model
 * @param CrawlRunsPostRequestBody The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCrawlRunsPostRequestBody(crawlRunsPostRequestBody: Partial<CrawlRunsPostRequestBody> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * Serializes information the current object
 * @param CrawlRunsPostRequestBody The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCrawlRunsPostRequestBody(writer: SerializationWriter, crawlRunsPostRequestBody: Partial<CrawlRunsPostRequestBody> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!crawlRunsPostRequestBody || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(crawlRunsPostRequestBody.additionalData);
}
/**
 * Uri template for the request builder.
 */
export const CrawlRunsRequestBuilderUriTemplate = "{+baseurl}/v1/crawl-runs{?created_at_from*,created_at_to*,cursor*,limit*,tags*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const CrawlRunsRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "createdAtFrom": "created_at_from",
    "createdAtTo": "created_at_to",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CrawlRunsRequestBuilderNavigationMetadata: Record<Exclude<keyof CrawlRunsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byRun_id: {
        requestsMetadata: WithRun_ItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithRun_ItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["run_id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const CrawlRunsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: CrawlRunsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUntypedNodeFromDiscriminatorValue,
        queryParametersMapper: CrawlRunsRequestBuilderGetQueryParametersMapper,
    },
    post: {
        uriTemplate: CrawlRunsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            422: createHTTPValidationErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUntypedNodeFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCrawlRunsPostRequestBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
